version: '3'

vars:
  FRONTEND_PORT:
    sh: node scripts/setup-dev-environment.js frontend
  BACKEND_PORT:
    sh: node scripts/setup-dev-environment.js backend

tasks:
  dev:
    desc: Start frontend and backend in hot-reload mode
    deps: [install]
    cmds:
      - task: dev:run

  dev:run:
    internal: true
    env:
      FRONTEND_PORT: '{{.FRONTEND_PORT}}'
      BACKEND_PORT: '{{.BACKEND_PORT}}'
      DISABLE_WORKTREE_ORPHAN_CLEANUP: '1'
      RUST_LOG: debug
    cmds:
      - |
        echo "Starting dev server..."
        echo "Frontend: http://localhost:{{.FRONTEND_PORT}}"
        echo "Backend: http://localhost:{{.BACKEND_PORT}}"
      - bunx concurrently --kill-others "task backend:watch" "task frontend:dev"

  install:
    desc: Install dependencies if needed
    status:
      - test -d node_modules
      - test -d frontend/node_modules
    cmds:
      - pnpm install

  frontend:dev:
    desc: Start frontend dev server
    dir: frontend
    env:
      FRONTEND_PORT: '{{.FRONTEND_PORT}}'
    cmds:
      - pnpm run dev -- --port {{.FRONTEND_PORT}} --host

  backend:watch:
    desc: Start backend with cargo-watch
    env:
      BACKEND_PORT: '{{.BACKEND_PORT}}'
      DISABLE_WORKTREE_ORPHAN_CLEANUP: '1'
      RUST_LOG: debug
    cmds:
      - cargo watch -w crates -x 'run --bin server'

  backend:run:
    desc: Run backend once (no watch)
    env:
      BACKEND_PORT: '{{.BACKEND_PORT}}'
      RUST_LOG: debug
    cmds:
      - cargo run --bin server

  check:
    desc: Run all checks (frontend + backend)
    cmds:
      - task: frontend:check
      - task: backend:check

  frontend:check:
    desc: Type-check frontend
    dir: frontend
    cmds:
      - pnpm run check

  backend:check:
    desc: Type-check backend
    cmds:
      - cargo check --workspace

  lint:
    desc: Lint all code
    cmds:
      - task: frontend:lint
      - task: backend:lint

  frontend:lint:
    desc: Lint frontend
    dir: frontend
    cmds:
      - pnpm run lint

  backend:lint:
    desc: Lint backend
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

  format:
    desc: Format all code
    cmds:
      - cargo fmt --all
      - cd frontend && pnpm run format

  test:
    desc: Run all tests
    cmds:
      - cargo test --workspace

  generate-types:
    desc: Generate TypeScript types from Rust
    cmds:
      - cargo run --bin generate_types

  prebuild:
    desc: Build for production
    cmds:
      - cargo build

  build:
    desc: Build for production (frontend first, then Rust to embed it)
    cmds:
      - cd frontend && pnpm run build
      - cargo build

  start:
    desc: Run build with PWA on port 4067
    deps: [build]
    env:
      BACKEND_PORT: '4067'
    cmds:
      - echo "Starting server on http://localhost:4067"
      - ./target/debug/server

  start:quick:
    desc: Run existing build without rebuilding
    env:
      BACKEND_PORT: '4067'
    cmds:
      - echo "Starting server on http://localhost:4067"
      - ./target/debug/server

  desktop:dev:
    desc: Start Tauri desktop app in dev mode with hot reload
    deps: [install]
    env:
      FRONTEND_PORT: '6769'
      BACKEND_PORT: '6770'
      TAURI_DEV: '1'
      DISABLE_WORKTREE_ORPHAN_CLEANUP: '1'
      RUST_LOG: debug
    cmds:
      - |
        echo "Starting Tauri dev mode..."
        echo "Frontend: http://localhost:6769"
        echo "Backend: http://localhost:6770"
      - bunx concurrently --kill-others "task backend:watch" "task frontend:dev" "cargo tauri dev"

  desktop:install:
    desc: Build and install desktop app (macOS)
    cmds:
      - cd frontend && pnpm run build
      - cargo tauri build
      - echo "Build complete. Installing..."
      - cp -r target/release/bundle/macos/Vibe.app /Applications/
      - echo "Installed to /Applications/Vibe.app"
